package substrate

import (
	"sync"
	"time"
)

// managedPolicyDate is the fixed creation/update date used for all bundled
// AWS managed policies.
var managedPolicyDate = time.Date(2015, 1, 1, 0, 0, 0, 0, time.UTC)

// managedPolicies holds the 47 bundled AWS managed policies.
// Policy documents sourced from https://docs.aws.amazon.com/aws-managed-policy/latest/reference/
// The slice itself is never mutated after package initialisation.
var managedPolicies = []*IAMPolicy{
	mp("AdministratorAccess", "ANPAIWMBCKSKIEE64ZLYK",
		"Provides full access to AWS services and resources.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{Effect: IAMEffectAllow, Action: StringOrSlice{"*"}, Resource: StringOrSlice{"*"}},
		}}),

	mp("PowerUserAccess", "ANPAJYRXTHIB4FOVS3ZXS",
		"Provides full access to AWS services and resources, but does not allow management of Users and groups.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect:    IAMEffectAllow,
				NotAction: StringOrSlice{"iam:*", "organizations:*", "account:*"},
				Resource:  StringOrSlice{"*"},
			},
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"account:GetAccountInformation",
					"account:GetGovCloudAccountInformation",
					"account:GetPrimaryEmail",
					"account:ListRegions",
					"iam:CreateServiceLinkedRole",
					"iam:DeleteServiceLinkedRole",
					"iam:ListRoles",
					"organizations:DescribeEffectivePolicy",
					"organizations:DescribeOrganization",
				},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("ReadOnlyAccess", "ANPAI3VAJF5ZCRZ7MCQE6",
		"Provides read-only access to AWS services and resources.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"acm:Describe*", "acm:Get*", "acm:List*",
					"autoscaling:Describe*",
					"cloudformation:Describe*", "cloudformation:Get*", "cloudformation:List*",
					"cloudwatch:Describe*", "cloudwatch:Get*", "cloudwatch:List*",
					"dynamodb:BatchGetItem", "dynamodb:Describe*", "dynamodb:List*",
					"dynamodb:GetItem", "dynamodb:Query", "dynamodb:Scan",
					"ec2:Describe*", "ec2:Get*",
					"ecs:Describe*", "ecs:List*",
					"eks:Describe*", "eks:List*",
					"elasticloadbalancing:Describe*",
					"iam:GenerateCredentialReport", "iam:GenerateServiceLastAccessedDetails",
					"iam:Get*", "iam:List*", "iam:SimulateCustomPolicy", "iam:SimulatePrincipalPolicy",
					"kinesis:Describe*", "kinesis:Get*", "kinesis:List*",
					"lambda:Get*", "lambda:List*",
					"logs:Describe*", "logs:Get*", "logs:List*",
					"rds:Describe*", "rds:List*",
					"s3:Get*", "s3:List*",
					"sns:Get*", "sns:List*",
					"sqs:Get*", "sqs:List*",
					"ssm:Describe*", "ssm:Get*", "ssm:List*",
					"tag:Get*",
				},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("IAMFullAccess", "ANPAI4JB77JXPKNVOJDU1",
		"Provides full access to IAM via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"iam:*",
					"organizations:DescribeAccount",
					"organizations:DescribeOrganization",
					"organizations:DescribeOrganizationalUnit",
					"organizations:DescribePolicy",
					"organizations:ListChildren",
					"organizations:ListParents",
					"organizations:ListPoliciesForTarget",
					"organizations:ListRoots",
					"organizations:ListPolicies",
					"organizations:ListTargetsForPolicy",
				},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("IAMReadOnlyAccess", "ANPAI4JB77JXPKNVOJDU2",
		"Provides read only access to IAM via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"iam:GenerateCredentialReport",
					"iam:GenerateServiceLastAccessedDetails",
					"iam:Get*",
					"iam:List*",
					"iam:SimulateCustomPolicy",
					"iam:SimulatePrincipalPolicy",
				},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("IAMUserChangePassword", "ANPAI4JB77JXPKNVOJDU3",
		"Provides the ability for an IAM user to change their own password.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:ChangePassword"},
				Resource: StringOrSlice{"arn:aws:iam::*:user/${aws:username}", "arn:aws:iam::*:user/*/${aws:username}"},
			},
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:GetAccountPasswordPolicy"},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("AmazonS3FullAccess", "ANPAIZTJ4ZTLGFQCJKQMQ",
		"Provides full access to all buckets via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"s3:*", "s3-object-lambda:*"},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("AmazonS3ReadOnlyAccess", "ANPAI6E2CYYMI4XI7AA5K",
		"Provides read only access to all buckets via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"s3:Get*", "s3:List*", "s3:Describe*",
					"s3-object-lambda:Get*", "s3-object-lambda:List*",
				},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("AmazonDynamoDBFullAccess", "ANPAINUGF2JSOSUY76KHW",
		"Provides full access to Amazon DynamoDB via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"dynamodb:*", "dax:*",
					"application-autoscaling:DeleteScalingPolicy",
					"application-autoscaling:DeregisterScalableTarget",
					"application-autoscaling:DescribeScalableTargets",
					"application-autoscaling:DescribeScalingActivities",
					"application-autoscaling:DescribeScalingPolicies",
					"application-autoscaling:PutScalingPolicy",
					"application-autoscaling:RegisterScalableTarget",
					"cloudwatch:DeleteAlarms",
					"cloudwatch:DescribeAlarmHistory",
					"cloudwatch:DescribeAlarms",
					"cloudwatch:DescribeAlarmsForMetric",
					"cloudwatch:GetMetricStatistics",
					"cloudwatch:ListMetrics",
					"cloudwatch:PutMetricAlarm",
					"cloudwatch:GetMetricData",
					"datapipeline:ActivatePipeline",
					"datapipeline:CreatePipeline",
					"datapipeline:DeletePipeline",
					"datapipeline:DescribeObjects",
					"datapipeline:DescribePipelines",
					"datapipeline:GetPipelineDefinition",
					"datapipeline:ListPipelines",
					"datapipeline:PutPipelineDefinition",
					"datapipeline:QueryObjects",
					"ec2:DescribeVpcs",
					"ec2:DescribeSubnets",
					"ec2:DescribeSecurityGroups",
					"iam:GetRole",
					"iam:ListRoles",
					"kms:DescribeKey",
					"kms:ListAliases",
					"sns:CreateTopic",
					"sns:DeleteTopic",
					"sns:ListSubscriptions",
					"sns:ListSubscriptionsByTopic",
					"sns:ListTopics",
					"sns:Subscribe",
					"sns:Unsubscribe",
					"sns:SetTopicAttributes",
					"lambda:CreateFunction",
					"lambda:ListFunctions",
					"lambda:ListEventSourceMappings",
					"lambda:CreateEventSourceMapping",
					"lambda:DeleteEventSourceMapping",
					"lambda:GetFunctionConfiguration",
					"lambda:DeleteFunction",
					"resource-groups:ListGroups",
					"resource-groups:ListGroupResources",
					"resource-groups:GetGroup",
					"resource-groups:GetGroupQuery",
					"resource-groups:DeleteGroup",
					"resource-groups:CreateGroup",
					"tag:GetResources",
					"kinesis:ListStreams",
					"kinesis:DescribeStream",
					"kinesis:DescribeStreamSummary",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"cloudwatch:GetInsightRuleReport"},
				Resource: StringOrSlice{"arn:aws:cloudwatch:*:*:insight-rule/DynamoDBContributorInsights*"},
			},
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:PassRole"},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringLike": {
						"iam:PassedToService": {
							"application-autoscaling.amazonaws.com",
							"application-autoscaling.amazonaws.com.cn",
							"dax.amazonaws.com",
						},
					},
				},
			},
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:CreateServiceLinkedRole"},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringEquals": {
						"iam:AWSServiceName": {
							"replication.dynamodb.amazonaws.com",
							"dax.amazonaws.com",
							"dynamodb.application-autoscaling.amazonaws.com",
							"contributorinsights.dynamodb.amazonaws.com",
							"kinesisreplication.dynamodb.amazonaws.com",
						},
					},
				},
			},
		}}),

	mp("AmazonDynamoDBReadOnlyAccess", "ANPAI2FHPNMQK74ZLU7YU",
		"Provides read only access to Amazon DynamoDB via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Sid:    "GeneralReadOnlyAccess",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"application-autoscaling:DescribeScalableTargets",
					"application-autoscaling:DescribeScalingActivities",
					"application-autoscaling:DescribeScalingPolicies",
					"cloudwatch:DescribeAlarmHistory",
					"cloudwatch:DescribeAlarms",
					"cloudwatch:DescribeAlarmsForMetric",
					"cloudwatch:GetMetricStatistics",
					"cloudwatch:ListMetrics",
					"cloudwatch:GetMetricData",
					"datapipeline:DescribeObjects",
					"datapipeline:DescribePipelines",
					"datapipeline:GetPipelineDefinition",
					"datapipeline:ListPipelines",
					"datapipeline:QueryObjects",
					"dynamodb:BatchGetItem",
					"dynamodb:Describe*",
					"dynamodb:List*",
					"dynamodb:GetAbacStatus",
					"dynamodb:GetItem",
					"dynamodb:GetResourcePolicy",
					"dynamodb:Query",
					"dynamodb:Scan",
					"dynamodb:PartiQLSelect",
					"dax:Describe*",
					"dax:List*",
					"dax:GetItem",
					"dax:BatchGetItem",
					"dax:Query",
					"dax:Scan",
					"ec2:DescribeVpcs",
					"ec2:DescribeSubnets",
					"ec2:DescribeSecurityGroups",
					"iam:GetRole",
					"iam:ListRoles",
					"kms:DescribeKey",
					"kms:ListAliases",
					"sns:ListSubscriptionsByTopic",
					"sns:ListTopics",
					"lambda:ListFunctions",
					"lambda:ListEventSourceMappings",
					"lambda:GetFunctionConfiguration",
					"resource-groups:ListGroups",
					"resource-groups:ListGroupResources",
					"resource-groups:GetGroup",
					"resource-groups:GetGroupQuery",
					"tag:GetResources",
					"kinesis:ListStreams",
					"kinesis:DescribeStream",
					"kinesis:DescribeStreamSummary",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Sid:      "CCIAccess",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"cloudwatch:GetInsightRuleReport"},
				Resource: StringOrSlice{"arn:aws:cloudwatch:*:*:insight-rule/DynamoDBContributorInsights*"},
			},
		}}),

	mp("AmazonEC2FullAccess", "ANPAI3VAJF5ZCRZ7MCQE7",
		"Provides full access to Amazon EC2 via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{Effect: IAMEffectAllow, Action: StringOrSlice{"ec2:*"}, Resource: StringOrSlice{"*"}},
			{Effect: IAMEffectAllow, Action: StringOrSlice{"elasticloadbalancing:*"}, Resource: StringOrSlice{"*"}},
			{Effect: IAMEffectAllow, Action: StringOrSlice{"cloudwatch:*"}, Resource: StringOrSlice{"*"}},
			{Effect: IAMEffectAllow, Action: StringOrSlice{"autoscaling:*"}, Resource: StringOrSlice{"*"}},
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:CreateServiceLinkedRole"},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringEquals": {
						"iam:AWSServiceName": {
							"autoscaling.amazonaws.com",
							"ec2scheduled.amazonaws.com",
							"elasticloadbalancing.amazonaws.com",
							"spot.amazonaws.com",
							"spotfleet.amazonaws.com",
							"transitgateway.amazonaws.com",
						},
					},
				},
			},
		}}),

	mp("AmazonEC2ReadOnlyAccess", "ANPAI3VAJF5ZCRZ7MCQE8",
		"Provides read only access to Amazon EC2 via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"ec2:Describe*", "ec2:GetSecurityGroupsForVpc"},
				Resource: StringOrSlice{"*"},
			},
			{Effect: IAMEffectAllow, Action: StringOrSlice{"elasticloadbalancing:Describe*"}, Resource: StringOrSlice{"*"}},
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"cloudwatch:ListMetrics", "cloudwatch:GetMetricStatistics", "cloudwatch:Describe*"},
				Resource: StringOrSlice{"*"},
			},
			{Effect: IAMEffectAllow, Action: StringOrSlice{"autoscaling:Describe*"}, Resource: StringOrSlice{"*"}},
		}}),

	mp("AWSLambda_FullAccess", "ANPAI4JB77JXPKNVOJDSS",
		"Grants full access to AWS Lambda service, AWS Lambda console features, and other related AWS services.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"cloudformation:DescribeStacks",
					"cloudformation:ListStackResources",
					"cloudwatch:ListMetrics",
					"cloudwatch:GetMetricData",
					"ec2:DescribeSecurityGroups",
					"ec2:DescribeSubnets",
					"ec2:DescribeVpcs",
					"kms:DescribeKey",
					"kms:ListAliases",
					"iam:GetPolicy",
					"iam:GetPolicyVersion",
					"iam:GetRole",
					"iam:GetRolePolicy",
					"iam:ListAttachedRolePolicies",
					"iam:ListRolePolicies",
					"iam:ListRoles",
					"lambda:*",
					"logs:DescribeLogGroups",
					"states:DescribeStateMachine",
					"states:ListStateMachines",
					"tag:GetResources",
					"xray:GetTraceSummaries",
					"xray:BatchGetTraces",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:PassRole"},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringEquals": {"iam:PassedToService": {"lambda.amazonaws.com"}},
				},
			},
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"logs:DescribeLogStreams",
					"logs:GetLogEvents",
					"logs:FilterLogEvents",
					"logs:StartLiveTail",
					"logs:StopLiveTail",
				},
				Resource: StringOrSlice{"arn:aws:logs:*:*:log-group:/aws/lambda/*"},
			},
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:CreateServiceLinkedRole"},
				Resource: StringOrSlice{"arn:aws:iam::*:role/aws-service-role/lambda.amazonaws.com/AWSServiceRoleForLambda"},
				Condition: map[string]map[string]StringOrSlice{
					"StringEquals": {"iam:AWSServiceName": {"lambda.amazonaws.com"}},
				},
			},
		}}),

	mp("AWSLambda_ReadOnlyAccess", "ANPAI4JB77JXPKNVOJDST",
		"Provides read only access to AWS Lambda service.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"cloudformation:DescribeStacks",
					"cloudformation:ListStacks",
					"cloudformation:ListStackResources",
					"cloudwatch:GetMetricData",
					"cloudwatch:ListMetrics",
					"ec2:DescribeSecurityGroups",
					"ec2:DescribeSubnets",
					"ec2:DescribeVpcs",
					"kms:ListAliases",
					"iam:GetPolicy",
					"iam:GetPolicyVersion",
					"iam:GetRole",
					"iam:GetRolePolicy",
					"iam:ListAttachedRolePolicies",
					"iam:ListRolePolicies",
					"iam:ListRoles",
					"logs:DescribeLogGroups",
					"lambda:Get*",
					"lambda:List*",
					"states:DescribeStateMachine",
					"states:ListStateMachines",
					"tag:GetResources",
					"xray:GetTraceSummaries",
					"xray:BatchGetTraces",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"logs:DescribeLogStreams",
					"logs:GetLogEvents",
					"logs:FilterLogEvents",
					"logs:StartQuery",
					"logs:StopQuery",
					"logs:DescribeQueries",
					"logs:GetLogGroupFields",
					"logs:GetLogRecord",
					"logs:GetQueryResults",
					"logs:StartLiveTail",
					"logs:StopLiveTail",
				},
				Resource: StringOrSlice{"arn:aws:logs:*:*:log-group:/aws/lambda/*"},
			},
		}}),

	mp("AmazonSQSFullAccess", "ANPAI65L554H3CIBMT4SC",
		"Provides full access to Amazon SQS via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{Effect: IAMEffectAllow, Action: StringOrSlice{"sqs:*"}, Resource: StringOrSlice{"*"}},
		}}),

	mp("AmazonSQSReadOnlyAccess", "ANPAI65L554H3CIBMT4SD",
		"Provides read only access to Amazon SQS via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Sid:    "AmazonSQSReadOnlyAccess",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"sqs:GetQueueAttributes",
					"sqs:GetQueueUrl",
					"sqs:ListDeadLetterSourceQueues",
					"sqs:ListQueues",
					"sqs:ListMessageMoveTasks",
					"sqs:ListQueueTags",
				},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("AmazonSNSFullAccess", "ANPAI7XKCFMBW3GBSUKRJ",
		"Provides full access to Amazon SNS via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{Sid: "SNSFullAccess", Effect: IAMEffectAllow, Action: StringOrSlice{"sns:*"}, Resource: StringOrSlice{"*"}},
			{
				Sid:    "SMSAccessViaSNS",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"sms-voice:DescribeVerifiedDestinationNumbers",
					"sms-voice:CreateVerifiedDestinationNumber",
					"sms-voice:SendDestinationNumberVerificationCode",
					"sms-voice:SendTextMessage",
					"sms-voice:DeleteVerifiedDestinationNumber",
					"sms-voice:VerifyDestinationNumber",
					"sms-voice:DescribeAccountAttributes",
					"sms-voice:DescribeSpendLimits",
					"sms-voice:DescribePhoneNumbers",
					"sms-voice:SetTextMessageSpendLimitOverride",
					"sms-voice:DescribeOptedOutNumbers",
					"sms-voice:DeleteOptedOutNumber",
				},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringEquals": {"aws:CalledViaLast": {"sns.amazonaws.com"}},
				},
			},
		}}),

	mp("AmazonSNSReadOnlyAccess", "ANPAI7XKCFMBW3GBSUKRK",
		"Provides read only access to Amazon SNS via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Sid:    "SNSReadOnlyAccess",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"sns:GetTopicAttributes",
					"sns:List*",
					"sns:CheckIfPhoneNumberIsOptedOut",
					"sns:GetEndpointAttributes",
					"sns:GetDataProtectionPolicy",
					"sns:GetPlatformApplicationAttributes",
					"sns:GetSMSAttributes",
					"sns:GetSMSSandboxAccountStatus",
					"sns:GetSubscriptionAttributes",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Sid:    "SMSAccessViaSNS",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"sms-voice:DescribeVerifiedDestinationNumbers",
					"sms-voice:DescribeAccountAttributes",
					"sms-voice:DescribeSpendLimits",
					"sms-voice:DescribePhoneNumbers",
					"sms-voice:DescribeOptedOutNumbers",
				},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringEquals": {"aws:CalledViaLast": {"sns.amazonaws.com"}},
				},
			},
		}}),

	mp("AmazonRDSFullAccess", "ANPAIUYBCLNL4GQJLGSL2",
		"Provides full access to Amazon RDS via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"rds:*",
					"application-autoscaling:DeleteScalingPolicy",
					"application-autoscaling:DeregisterScalableTarget",
					"application-autoscaling:DescribeScalableTargets",
					"application-autoscaling:DescribeScalingActivities",
					"application-autoscaling:DescribeScalingPolicies",
					"application-autoscaling:PutScalingPolicy",
					"application-autoscaling:RegisterScalableTarget",
					"cloudwatch:DescribeAlarms",
					"cloudwatch:GetMetricStatistics",
					"cloudwatch:PutMetricAlarm",
					"cloudwatch:DeleteAlarms",
					"cloudwatch:ListMetrics",
					"cloudwatch:GetMetricData",
					"ec2:DescribeAccountAttributes",
					"ec2:DescribeAvailabilityZones",
					"ec2:DescribeCoipPools",
					"ec2:DescribeInternetGateways",
					"ec2:DescribeLocalGatewayRouteTablePermissions",
					"ec2:DescribeLocalGatewayRouteTables",
					"ec2:DescribeLocalGatewayRouteTableVpcAssociations",
					"ec2:DescribeLocalGateways",
					"ec2:DescribeSecurityGroups",
					"ec2:DescribeSubnets",
					"ec2:DescribeVpcAttribute",
					"ec2:DescribeVpcs",
					"ec2:GetCoipPoolUsage",
					"sns:ListSubscriptions",
					"sns:ListTopics",
					"sns:Publish",
					"logs:DescribeLogStreams",
					"logs:GetLogEvents",
					"outposts:GetOutpostInstanceTypes",
					"devops-guru:GetResourceCollection",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"pi:*"},
				Resource: StringOrSlice{"arn:aws:pi:*:*:metrics/rds/*", "arn:aws:pi:*:*:perf-reports/rds/*"},
			},
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:CreateServiceLinkedRole"},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringLike": {"iam:AWSServiceName": {"rds.amazonaws.com", "rds.application-autoscaling.amazonaws.com"}},
				},
			},
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"devops-guru:SearchInsights", "devops-guru:ListAnomaliesForInsight"},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"ForAllValues:StringEquals": {"devops-guru:ServiceNames": {"RDS"}},
					"Null":                      {"devops-guru:ServiceNames": {"false"}},
				},
			},
		}}),

	mp("AmazonRDSReadOnlyAccess", "ANPAIUYBCLNL4GQJLGSL3",
		"Provides read only access to Amazon RDS via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"rds:Describe*",
					"rds:ListTagsForResource",
					"ec2:DescribeAccountAttributes",
					"ec2:DescribeAvailabilityZones",
					"ec2:DescribeInternetGateways",
					"ec2:DescribeSecurityGroups",
					"ec2:DescribeSubnets",
					"ec2:DescribeVpcAttribute",
					"ec2:DescribeVpcs",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"cloudwatch:GetMetricStatistics",
					"cloudwatch:ListMetrics",
					"cloudwatch:GetMetricData",
					"logs:DescribeLogStreams",
					"logs:GetLogEvents",
					"devops-guru:GetResourceCollection",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"devops-guru:SearchInsights", "devops-guru:ListAnomaliesForInsight"},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"ForAllValues:StringEquals": {"devops-guru:ServiceNames": {"RDS"}},
					"Null":                      {"devops-guru:ServiceNames": {"false"}},
				},
			},
		}}),

	mp("AmazonVPCFullAccess", "ANPAI4JB77JXPKNVOJDTA",
		"Provides full access to Amazon VPC via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Sid:    "AmazonVPCFullAccess",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"ec2:AcceptVpcPeeringConnection",
					"ec2:AcceptVpcEndpointConnections",
					"ec2:AllocateAddress",
					"ec2:AssignIpv6Addresses",
					"ec2:AssignPrivateIpAddresses",
					"ec2:AssociateAddress",
					"ec2:AssociateDhcpOptions",
					"ec2:AssociateRouteTable",
					"ec2:AssociateSecurityGroupVpc",
					"ec2:AssociateSubnetCidrBlock",
					"ec2:AssociateVpcCidrBlock",
					"ec2:AttachClassicLinkVpc",
					"ec2:AttachInternetGateway",
					"ec2:AttachNetworkInterface",
					"ec2:AttachVpnGateway",
					"ec2:AuthorizeSecurityGroupEgress",
					"ec2:AuthorizeSecurityGroupIngress",
					"ec2:CreateCarrierGateway",
					"ec2:CreateCustomerGateway",
					"ec2:CreateDefaultSubnet",
					"ec2:CreateDefaultVpc",
					"ec2:CreateDhcpOptions",
					"ec2:CreateEgressOnlyInternetGateway",
					"ec2:CreateFlowLogs",
					"ec2:CreateInternetGateway",
					"ec2:CreateLocalGatewayRouteTableVpcAssociation",
					"ec2:CreateNatGateway",
					"ec2:CreateNetworkAcl",
					"ec2:CreateNetworkAclEntry",
					"ec2:CreateNetworkInterface",
					"ec2:CreateNetworkInterfacePermission",
					"ec2:CreateRoute",
					"ec2:CreateRouteTable",
					"ec2:CreateSecurityGroup",
					"ec2:CreateSubnet",
					"ec2:CreateTags",
					"ec2:CreateVpc",
					"ec2:CreateVpcEndpoint",
					"ec2:CreateVpcEndpointConnectionNotification",
					"ec2:CreateVpcEndpointServiceConfiguration",
					"ec2:CreateVpcPeeringConnection",
					"ec2:CreateVpnConnection",
					"ec2:CreateVpnConnectionRoute",
					"ec2:CreateVpnGateway",
					"ec2:DeleteCarrierGateway",
					"ec2:DeleteCustomerGateway",
					"ec2:DeleteDhcpOptions",
					"ec2:DeleteEgressOnlyInternetGateway",
					"ec2:DeleteFlowLogs",
					"ec2:DeleteInternetGateway",
					"ec2:DeleteLocalGatewayRouteTableVpcAssociation",
					"ec2:DeleteNatGateway",
					"ec2:DeleteNetworkAcl",
					"ec2:DeleteNetworkAclEntry",
					"ec2:DeleteNetworkInterface",
					"ec2:DeleteNetworkInterfacePermission",
					"ec2:DeleteRoute",
					"ec2:DeleteRouteTable",
					"ec2:DeleteSecurityGroup",
					"ec2:DeleteSubnet",
					"ec2:DeleteTags",
					"ec2:DeleteVpc",
					"ec2:DeleteVpcEndpoints",
					"ec2:DeleteVpcEndpointConnectionNotifications",
					"ec2:DeleteVpcEndpointServiceConfigurations",
					"ec2:DeleteVpcPeeringConnection",
					"ec2:DeleteVpnConnection",
					"ec2:DeleteVpnConnectionRoute",
					"ec2:DeleteVpnGateway",
					"ec2:DescribeAccountAttributes",
					"ec2:DescribeAddresses",
					"ec2:DescribeAvailabilityZones",
					"ec2:DescribeCarrierGateways",
					"ec2:DescribeClassicLinkInstances",
					"ec2:DescribeCustomerGateways",
					"ec2:DescribeDhcpOptions",
					"ec2:DescribeEgressOnlyInternetGateways",
					"ec2:DescribeFlowLogs",
					"ec2:DescribeInstances",
					"ec2:DescribeInternetGateways",
					"ec2:DescribeIpv6Pools",
					"ec2:DescribeLocalGatewayRouteTables",
					"ec2:DescribeLocalGatewayRouteTableVpcAssociations",
					"ec2:DescribeKeyPairs",
					"ec2:DescribeMovingAddresses",
					"ec2:DescribeNatGateways",
					"ec2:DescribeNetworkAcls",
					"ec2:DescribeNetworkInterfaceAttribute",
					"ec2:DescribeNetworkInterfacePermissions",
					"ec2:DescribeNetworkInterfaces",
					"ec2:DescribePrefixLists",
					"ec2:DescribeRouteTables",
					"ec2:DescribeSecurityGroupReferences",
					"ec2:DescribeSecurityGroupRules",
					"ec2:DescribeSecurityGroups",
					"ec2:DescribeSecurityGroupVpcAssociations",
					"ec2:DescribeStaleSecurityGroups",
					"ec2:DescribeSubnets",
					"ec2:DescribeTags",
					"ec2:DescribeVpcAttribute",
					"ec2:DescribeVpcClassicLink",
					"ec2:DescribeVpcClassicLinkDnsSupport",
					"ec2:DescribeVpcEndpointConnectionNotifications",
					"ec2:DescribeVpcEndpointConnections",
					"ec2:DescribeVpcEndpoints",
					"ec2:DescribeVpcEndpointServiceConfigurations",
					"ec2:DescribeVpcEndpointServicePermissions",
					"ec2:DescribeVpcEndpointServices",
					"ec2:DescribeVpcPeeringConnections",
					"ec2:DescribeVpcs",
					"ec2:DescribeVpnConnections",
					"ec2:DescribeVpnGateways",
					"ec2:DetachClassicLinkVpc",
					"ec2:DetachInternetGateway",
					"ec2:DetachNetworkInterface",
					"ec2:DetachVpnGateway",
					"ec2:DisableVgwRoutePropagation",
					"ec2:DisableVpcClassicLink",
					"ec2:DisableVpcClassicLinkDnsSupport",
					"ec2:DisassociateAddress",
					"ec2:DisassociateRouteTable",
					"ec2:DisassociateSecurityGroupVpc",
					"ec2:DisassociateSubnetCidrBlock",
					"ec2:DisassociateVpcCidrBlock",
					"ec2:EnableVgwRoutePropagation",
					"ec2:EnableVpcClassicLink",
					"ec2:EnableVpcClassicLinkDnsSupport",
					"ec2:GetSecurityGroupsForVpc",
					"ec2:ModifyNetworkInterfaceAttribute",
					"ec2:ModifySecurityGroupRules",
					"ec2:ModifySubnetAttribute",
					"ec2:ModifyVpcAttribute",
					"ec2:ModifyVpcEndpoint",
					"ec2:ModifyVpcEndpointConnectionNotification",
					"ec2:ModifyVpcEndpointServiceConfiguration",
					"ec2:ModifyVpcEndpointServicePermissions",
					"ec2:ModifyVpcPeeringConnectionOptions",
					"ec2:ModifyVpcTenancy",
					"ec2:MoveAddressToVpc",
					"ec2:RejectVpcEndpointConnections",
					"ec2:RejectVpcPeeringConnection",
					"ec2:ReleaseAddress",
					"ec2:ReplaceNetworkAclAssociation",
					"ec2:ReplaceNetworkAclEntry",
					"ec2:ReplaceRoute",
					"ec2:ReplaceRouteTableAssociation",
					"ec2:ResetNetworkInterfaceAttribute",
					"ec2:RestoreAddressToClassic",
					"ec2:RevokeSecurityGroupEgress",
					"ec2:RevokeSecurityGroupIngress",
					"ec2:UnassignIpv6Addresses",
					"ec2:UnassignPrivateIpAddresses",
					"ec2:UpdateSecurityGroupRuleDescriptionsEgress",
					"ec2:UpdateSecurityGroupRuleDescriptionsIngress",
				},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("AmazonVPCReadOnlyAccess", "ANPAI4JB77JXPKNVOJDTB",
		"Provides read only access to Amazon VPC via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Sid:    "AmazonVPCReadOnlyAccess",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"ec2:DescribeAccountAttributes",
					"ec2:DescribeAddresses",
					"ec2:DescribeCarrierGateways",
					"ec2:DescribeClassicLinkInstances",
					"ec2:DescribeCustomerGateways",
					"ec2:DescribeDhcpOptions",
					"ec2:DescribeEgressOnlyInternetGateways",
					"ec2:DescribeFlowLogs",
					"ec2:DescribeInternetGateways",
					"ec2:DescribeLocalGatewayRouteTables",
					"ec2:DescribeLocalGatewayRouteTableVpcAssociations",
					"ec2:DescribeMovingAddresses",
					"ec2:DescribeNatGateways",
					"ec2:DescribeNetworkAcls",
					"ec2:DescribeNetworkInterfaceAttribute",
					"ec2:DescribeNetworkInterfacePermissions",
					"ec2:DescribeNetworkInterfaces",
					"ec2:DescribePrefixLists",
					"ec2:DescribeRouteTables",
					"ec2:DescribeSecurityGroupReferences",
					"ec2:DescribeSecurityGroupRules",
					"ec2:DescribeSecurityGroups",
					"ec2:DescribeSecurityGroupVpcAssociations",
					"ec2:DescribeStaleSecurityGroups",
					"ec2:DescribeSubnets",
					"ec2:DescribeTags",
					"ec2:DescribeVpcAttribute",
					"ec2:DescribeVpcClassicLink",
					"ec2:DescribeVpcClassicLinkDnsSupport",
					"ec2:DescribeVpcEndpoints",
					"ec2:DescribeVpcEndpointConnectionNotifications",
					"ec2:DescribeVpcEndpointConnections",
					"ec2:DescribeVpcEndpointServiceConfigurations",
					"ec2:DescribeVpcEndpointServicePermissions",
					"ec2:DescribeVpcEndpointServices",
					"ec2:DescribeVpcPeeringConnections",
					"ec2:DescribeVpcs",
					"ec2:DescribeVpnConnections",
					"ec2:DescribeVpnGateways",
					"ec2:GetSecurityGroupsForVpc",
				},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("AmazonECS_FullAccess", "ANPAI4JB77JXPKNVOJDTC",
		"Provides administrative access to Amazon ECS resources and enables ECS features through access to other AWS service resources.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"application-autoscaling:DeleteScalingPolicy",
					"application-autoscaling:DeregisterScalableTarget",
					"application-autoscaling:DescribeScalableTargets",
					"application-autoscaling:DescribeScalingActivities",
					"application-autoscaling:DescribeScalingPolicies",
					"application-autoscaling:PutScalingPolicy",
					"application-autoscaling:RegisterScalableTarget",
					"appmesh:DescribeMesh",
					"appmesh:DescribeVirtualNode",
					"appmesh:ListMeshes",
					"appmesh:ListVirtualNodes",
					"autoscaling:CreateAutoScalingGroup",
					"autoscaling:DeleteAutoScalingGroup",
					"autoscaling:Describe*",
					"autoscaling:UpdateAutoScalingGroup",
					"cloudformation:CreateStack",
					"cloudformation:DeleteStack",
					"cloudformation:DescribeStack*",
					"cloudformation:UpdateStack",
					"cloudwatch:DeleteAlarms",
					"cloudwatch:DescribeAlarms",
					"cloudwatch:GetMetricStatistics",
					"cloudwatch:PutMetricAlarm",
					"codedeploy:BatchGetApplicationRevisions",
					"codedeploy:BatchGetApplications",
					"codedeploy:BatchGetDeploymentGroups",
					"codedeploy:BatchGetDeployments",
					"codedeploy:ContinueDeployment",
					"codedeploy:CreateApplication",
					"codedeploy:CreateDeployment",
					"codedeploy:CreateDeploymentConfig",
					"codedeploy:CreateDeploymentGroup",
					"codedeploy:DeleteApplication",
					"codedeploy:DeleteDeploymentGroup",
					"codedeploy:DeregisterOnPremisesInstance",
					"codedeploy:GetApplication",
					"codedeploy:GetApplicationRevision",
					"codedeploy:GetDeployment",
					"codedeploy:GetDeploymentConfig",
					"codedeploy:GetDeploymentGroup",
					"codedeploy:GetDeploymentTarget",
					"codedeploy:GetOnPremisesInstance",
					"codedeploy:ListApplicationRevisions",
					"codedeploy:ListApplications",
					"codedeploy:ListDeploymentConfigs",
					"codedeploy:ListDeploymentGroups",
					"codedeploy:ListDeployments",
					"codedeploy:ListDeploymentTargets",
					"codedeploy:ListOnPremisesInstances",
					"codedeploy:ListTagsForResource",
					"codedeploy:RegisterApplicationRevision",
					"codedeploy:StopDeployment",
					"codedeploy:UpdateApplication",
					"codedeploy:UpdateDeploymentGroup",
					"ec2:AssociateRouteTable",
					"ec2:AttachInternetGateway",
					"ec2:AuthorizeSecurityGroupIngress",
					"ec2:CancelSpotFleetRequests",
					"ec2:CreateInternetGateway",
					"ec2:CreateLaunchTemplate",
					"ec2:CreateRoute",
					"ec2:CreateRouteTable",
					"ec2:CreateSecurityGroup",
					"ec2:CreateSubnet",
					"ec2:CreateVpc",
					"ec2:DeleteLaunchTemplate",
					"ec2:DeleteSubnet",
					"ec2:DeleteVpc",
					"ec2:Describe*",
					"ec2:DetachInternetGateway",
					"ec2:DisassociateRouteTable",
					"ec2:ModifySubnetAttribute",
					"ec2:ModifyVpcAttribute",
					"ec2:RequestSpotFleet",
					"ec2:RunInstances",
					"ecs:*",
					"elasticloadbalancing:AddListenerCertificates",
					"elasticloadbalancing:AddTags",
					"elasticloadbalancing:CreateListener",
					"elasticloadbalancing:CreateLoadBalancer",
					"elasticloadbalancing:CreateRule",
					"elasticloadbalancing:CreateTargetGroup",
					"elasticloadbalancing:DeleteListener",
					"elasticloadbalancing:DeleteLoadBalancer",
					"elasticloadbalancing:DeleteRule",
					"elasticloadbalancing:DeleteTargetGroup",
					"elasticloadbalancing:DeregisterTargets",
					"elasticloadbalancing:Describe*",
					"elasticloadbalancing:ModifyListener",
					"elasticloadbalancing:ModifyLoadBalancerAttributes",
					"elasticloadbalancing:ModifyRule",
					"elasticloadbalancing:ModifyTargetGroup",
					"elasticloadbalancing:ModifyTargetGroupAttributes",
					"elasticloadbalancing:RegisterTargets",
					"elasticloadbalancing:RemoveListenerCertificates",
					"elasticloadbalancing:RemoveTags",
					"elasticloadbalancing:SetIpAddressType",
					"elasticloadbalancing:SetRulePriorities",
					"elasticloadbalancing:SetSecurityGroups",
					"elasticloadbalancing:SetSubnets",
					"events:DeleteRule",
					"events:DescribeRule",
					"events:ListRuleNamesByTarget",
					"events:ListRules",
					"events:ListTargetsByRule",
					"events:PutRule",
					"events:PutTargets",
					"events:RemoveTargets",
					"iam:ListAttachedRolePolicies",
					"iam:ListInstanceProfiles",
					"iam:ListRoles",
					"lambda:ListFunctions",
					"logs:CreateLogGroup",
					"logs:DescribeLogGroups",
					"logs:FilterLogEvents",
					"route53:CreateHostedZone",
					"route53:DeleteHostedZone",
					"route53:GetHealthCheck",
					"route53:GetHostedZone",
					"route53:ListHostedZonesByName",
					"servicediscovery:CreatePrivateDnsNamespace",
					"servicediscovery:CreateService",
					"servicediscovery:DeleteService",
					"servicediscovery:GetNamespace",
					"servicediscovery:GetOperation",
					"servicediscovery:GetService",
					"servicediscovery:ListNamespaces",
					"servicediscovery:ListServices",
					"servicediscovery:UpdateService",
					"sns:ListTopics",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Sid:      "SSMPolicy",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"ssm:GetParameter", "ssm:GetParameters", "ssm:GetParametersByPath"},
				Resource: StringOrSlice{"arn:aws:ssm:*:*:parameter/aws/service/ecs*"},
			},
			{
				Sid:    "ManagedCloudformationResourcesCleanupPolicy",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"ec2:DeleteInternetGateway",
					"ec2:DeleteRoute",
					"ec2:DeleteRouteTable",
					"ec2:DeleteSecurityGroup",
				},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringLike": {"ec2:ResourceTag/aws:cloudformation:stack-name": {"EC2ContainerService-*"}},
				},
			},
			{
				Sid:      "TasksPassRolePolicy",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:PassRole"},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringLike": {"iam:PassedToService": {"ecs-tasks.amazonaws.com"}},
				},
			},
			{
				Sid:      "InfrastructurePassRolePolicy",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:PassRole"},
				Resource: StringOrSlice{"arn:aws:iam::*:role/ecsInfrastructureRole"},
				Condition: map[string]map[string]StringOrSlice{
					"StringEquals": {"iam:PassedToService": {"ecs.amazonaws.com"}},
				},
			},
			{
				Sid:      "InstancePassRolePolicy",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:PassRole"},
				Resource: StringOrSlice{"arn:aws:iam::*:role/ecsInstanceRole*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringLike": {"iam:PassedToService": {"ec2.amazonaws.com", "ec2.amazonaws.com.cn"}},
				},
			},
			{
				Sid:      "AutoScalingPassRolePolicy",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:PassRole"},
				Resource: StringOrSlice{"arn:aws:iam::*:role/ecsAutoscaleRole*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringLike": {
						"iam:PassedToService": {
							"application-autoscaling.amazonaws.com",
							"application-autoscaling.amazonaws.com.cn",
						},
					},
				},
			},
			{
				Sid:      "ServiceLinkedRoleCreationPolicy",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:CreateServiceLinkedRole"},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringLike": {
						"iam:AWSServiceName": {
							"ecs.amazonaws.com",
							"autoscaling.amazonaws.com",
							"ecs.application-autoscaling.amazonaws.com",
							"spot.amazonaws.com",
							"spotfleet.amazonaws.com",
						},
					},
				},
			},
			{
				Sid:      "ELBTaggingPolicy",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"elasticloadbalancing:AddTags"},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringEquals": {
						"elasticloadbalancing:CreateAction": {
							"CreateTargetGroup",
							"CreateRule",
							"CreateListener",
							"CreateLoadBalancer",
						},
					},
				},
			},
		}}),

	mp("AmazonECS_ReadOnly", "ANPAI4JB77JXPKNVOJDTD",
		"Provides read only access to Amazon ECS.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{Effect: IAMEffectAllow, Action: StringOrSlice{"ecs:Describe*", "ecs:List*"}, Resource: StringOrSlice{"*"}},
		}}),

	mp("AmazonEKSClusterPolicy", "ANPAI3VAJF5ZCRZ7MCQG1",
		"This policy provides Kubernetes the permissions it requires to manage resources on your behalf.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Sid:    "AmazonEKSClusterPolicy",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"autoscaling:DescribeAutoScalingGroups",
					"autoscaling:UpdateAutoScalingGroup",
					"ec2:AttachVolume",
					"ec2:AuthorizeSecurityGroupIngress",
					"ec2:CreateRoute",
					"ec2:CreateSecurityGroup",
					"ec2:CreateTags",
					"ec2:CreateVolume",
					"ec2:DeleteRoute",
					"ec2:DeleteSecurityGroup",
					"ec2:DeleteVolume",
					"ec2:DescribeInstances",
					"ec2:DescribeRouteTables",
					"ec2:DescribeSecurityGroups",
					"ec2:DescribeSubnets",
					"ec2:DescribeVolumes",
					"ec2:DescribeVolumesModifications",
					"ec2:DescribeVpcs",
					"ec2:DescribeDhcpOptions",
					"ec2:DescribeNetworkInterfaces",
					"ec2:DescribeAvailabilityZones",
					"ec2:DescribeAccountAttributes",
					"ec2:DescribeAddresses",
					"ec2:DescribeInternetGateways",
					"ec2:DescribeInstanceTopology",
					"ec2:DetachVolume",
					"ec2:ModifyInstanceAttribute",
					"ec2:ModifyVolume",
					"ec2:RevokeSecurityGroupIngress",
					"elasticloadbalancing:AddTags",
					"elasticloadbalancing:ApplySecurityGroupsToLoadBalancer",
					"elasticloadbalancing:AttachLoadBalancerToSubnets",
					"elasticloadbalancing:ConfigureHealthCheck",
					"elasticloadbalancing:CreateListener",
					"elasticloadbalancing:CreateLoadBalancer",
					"elasticloadbalancing:CreateLoadBalancerListeners",
					"elasticloadbalancing:CreateLoadBalancerPolicy",
					"elasticloadbalancing:CreateTargetGroup",
					"elasticloadbalancing:DeleteListener",
					"elasticloadbalancing:DeleteLoadBalancer",
					"elasticloadbalancing:DeleteLoadBalancerListeners",
					"elasticloadbalancing:DeleteTargetGroup",
					"elasticloadbalancing:DeregisterInstancesFromLoadBalancer",
					"elasticloadbalancing:DeregisterTargets",
					"elasticloadbalancing:DescribeListeners",
					"elasticloadbalancing:DescribeLoadBalancerAttributes",
					"elasticloadbalancing:DescribeLoadBalancerPolicies",
					"elasticloadbalancing:DescribeLoadBalancers",
					"elasticloadbalancing:DescribeTargetGroupAttributes",
					"elasticloadbalancing:DescribeTargetGroups",
					"elasticloadbalancing:DescribeTargetHealth",
					"elasticloadbalancing:DetachLoadBalancerFromSubnets",
					"elasticloadbalancing:ModifyListener",
					"elasticloadbalancing:ModifyLoadBalancerAttributes",
					"elasticloadbalancing:ModifyTargetGroup",
					"elasticloadbalancing:ModifyTargetGroupAttributes",
					"elasticloadbalancing:RegisterInstancesWithLoadBalancer",
					"elasticloadbalancing:RegisterTargets",
					"elasticloadbalancing:SetLoadBalancerPoliciesForBackendServer",
					"elasticloadbalancing:SetLoadBalancerPoliciesOfListener",
					"kms:DescribeKey",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Sid:      "AmazonEKSClusterPolicySLRCreate",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:CreateServiceLinkedRole"},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringEquals": {"iam:AWSServiceName": {"elasticloadbalancing.amazonaws.com"}},
				},
			},
			{
				Sid:      "AmazonEKSClusterPolicyENIDelete",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"ec2:DeleteNetworkInterface"},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringEquals": {"ec2:ResourceTag/eks:eni:owner": {"amazon-vpc-cni"}},
				},
			},
		}}),

	mp("AmazonEKSWorkerNodePolicy", "ANPAI3VAJF5ZCRZ7MCQG2",
		"This policy allows Amazon EKS worker nodes to connect to Amazon EKS Clusters.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Sid:    "WorkerNodePermissions",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"ec2:DescribeInstances",
					"ec2:DescribeInstanceTypes",
					"ec2:DescribeRouteTables",
					"ec2:DescribeSecurityGroups",
					"ec2:DescribeSubnets",
					"ec2:DescribeVolumes",
					"ec2:DescribeVolumesModifications",
					"ec2:DescribeVpcs",
					"eks:DescribeCluster",
					"eks-auth:AssumeRoleForPodIdentity",
				},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("AWSCloudFormationFullAccess", "ANPAI4JB77JXPKNVOJDV1",
		"Provides full access to AWS CloudFormation.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{Effect: IAMEffectAllow, Action: StringOrSlice{"cloudformation:*"}, Resource: StringOrSlice{"*"}},
		}}),

	mp("AWSCloudFormationReadOnlyAccess", "ANPAI4JB77JXPKNVOJDV2",
		"Provides access to AWS CloudFormation via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"cloudformation:Describe*",
					"cloudformation:BatchDescribe*",
					"cloudformation:EstimateTemplateCost",
					"cloudformation:Get*",
					"cloudformation:List*",
					"cloudformation:ValidateTemplate",
					"cloudformation:Detect*",
				},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("CloudWatchFullAccess", "ANPAI4JB77JXPKNVOJDW1",
		"Provides full access to CloudWatch.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"autoscaling:Describe*",
					"cloudwatch:*",
					"logs:*",
					"sns:*",
					"iam:GetPolicy",
					"iam:GetPolicyVersion",
					"iam:GetRole",
					"oam:ListSinks",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:CreateServiceLinkedRole"},
				Resource: StringOrSlice{"arn:aws:iam::*:role/aws-service-role/events.amazonaws.com/AWSServiceRoleForCloudWatchEvents*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringLike": {"iam:AWSServiceName": {"events.amazonaws.com"}},
				},
			},
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"oam:ListAttachedLinks"},
				Resource: StringOrSlice{"arn:aws:oam:*:*:sink/*"},
			},
		}}),

	mp("CloudWatchReadOnlyAccess", "ANPAI4JB77JXPKNVOJDW2",
		"Provides read only access to CloudWatch.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Sid:    "CloudWatchReadOnlyAccessPermissions",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"application-autoscaling:DescribeScalingPolicies",
					"autoscaling:Describe*",
					"cloudwatch:BatchGet*",
					"cloudwatch:Describe*",
					"cloudwatch:GenerateQuery",
					"cloudwatch:Get*",
					"cloudwatch:List*",
					"logs:Get*",
					"logs:List*",
					"logs:StartQuery",
					"logs:StopQuery",
					"logs:Describe*",
					"logs:TestMetricFilter",
					"logs:FilterLogEvents",
					"logs:StartLiveTail",
					"logs:StopLiveTail",
					"oam:ListSinks",
					"sns:Get*",
					"sns:List*",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Sid:      "OAMReadPermissions",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"oam:ListAttachedLinks"},
				Resource: StringOrSlice{"arn:aws:oam:*:*:sink/*"},
			},
		}}),

	mp("AmazonElastiCacheFullAccess", "ANPAI4JB77JXPKNVOJDX1",
		"Provides full access to Amazon ElastiCache via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Sid:      "ElastiCacheManagementActions",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"elasticache:*"},
				Resource: StringOrSlice{"*"},
			},
			{
				Sid:      "CreateServiceLinkedRole",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:CreateServiceLinkedRole"},
				Resource: StringOrSlice{"arn:aws:iam::*:role/aws-service-role/elasticache.amazonaws.com/AWSServiceRoleForElastiCache"},
				Condition: map[string]map[string]StringOrSlice{
					"StringLike": {"iam:AWSServiceName": {"elasticache.amazonaws.com"}},
				},
			},
			{
				Sid:      "AllowAccessToEc2",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"ec2:DescribeVpcs", "ec2:DescribeSubnets", "ec2:DescribeSecurityGroups"},
				Resource: StringOrSlice{"*"},
			},
			{
				Sid:      "AllowAccessToKMS",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"kms:DescribeKey", "kms:ListAliases", "kms:ListKeys"},
				Resource: StringOrSlice{"*"},
			},
			{
				Sid:      "AllowAccessToCloudWatch",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"cloudwatch:GetMetricStatistics", "cloudwatch:GetMetricData"},
				Resource: StringOrSlice{"*"},
			},
			{
				Sid:    "AllowAccessToAutoScaling",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"application-autoscaling:DescribeScalableTargets",
					"application-autoscaling:DescribeScheduledActions",
					"application-autoscaling:DescribeScalingPolicies",
					"application-autoscaling:DescribeScalingActivities",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Sid:      "DescribeLogGroups",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"logs:DescribeLogGroups"},
				Resource: StringOrSlice{"*"},
			},
			{
				Sid:      "DescribeS3Buckets",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"s3:ListAllMyBuckets"},
				Resource: StringOrSlice{"*"},
			},
			{
				Sid:      "AllowAccessToSNS",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"sns:ListTopics"},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("AmazonElastiCacheReadOnlyAccess", "ANPAI4JB77JXPKNVOJDX2",
		"Provides read only access to Amazon ElastiCache via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"elasticache:Describe*"},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("AWSBatchFullAccess", "ANPAI4JB77JXPKNVOJDY1",
		"Provides full access for AWS Batch resources.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"batch:*",
					"cloudwatch:GetMetricStatistics",
					"ec2:DescribeSubnets",
					"ec2:DescribeSecurityGroups",
					"ec2:DescribeKeyPairs",
					"ec2:DescribeVpcs",
					"ec2:DescribeImages",
					"ec2:DescribeLaunchTemplates",
					"ec2:DescribeLaunchTemplateVersions",
					"ecs:DescribeClusters",
					"ecs:Describe*",
					"ecs:List*",
					"eks:DescribeCluster",
					"eks:ListClusters",
					"logs:Describe*",
					"logs:Get*",
					"logs:TestMetricFilter",
					"logs:FilterLogEvents",
					"iam:ListInstanceProfiles",
					"iam:ListRoles",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{"iam:PassRole"},
				Resource: StringOrSlice{
					"arn:aws:iam::*:role/AWSBatchServiceRole",
					"arn:aws:iam::*:role/service-role/AWSBatchServiceRole",
					"arn:aws:iam::*:role/ecsInstanceRole",
					"arn:aws:iam::*:instance-profile/ecsInstanceRole",
					"arn:aws:iam::*:role/iaws-ec2-spot-fleet-role",
					"arn:aws:iam::*:role/aws-ec2-spot-fleet-role",
					"arn:aws:iam::*:role/AWSBatchJobRole*",
				},
			},
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:CreateServiceLinkedRole"},
				Resource: StringOrSlice{"arn:aws:iam::*:role/*Batch*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringEquals": {"iam:AWSServiceName": {"batch.amazonaws.com"}},
				},
			},
		}}),

	mp("AWSBatchReadOnly", "ANPAI4JB77JXPKNVOJDY2",
		"Provides read only access to AWS Batch.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"batch:Describe*", "batch:List*"},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("AmazonKinesisFullAccess", "ANPAI4JB77JXPKNVOJDZ1",
		"Provides full access to all streams via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{Effect: IAMEffectAllow, Action: StringOrSlice{"kinesis:*"}, Resource: StringOrSlice{"*"}},
		}}),

	mp("AmazonKinesisReadOnlyAccess", "ANPAI4JB77JXPKNVOJDZ2",
		"Provides read only access to all streams via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"kinesis:Get*", "kinesis:List*", "kinesis:Describe*"},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("SecretsManagerReadWrite", "ANPAI4JB77JXPKNVOJEA1",
		"Provides read/write access to AWS Secrets Manager via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Sid:    "BasePermissions",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"secretsmanager:*",
					"cloudformation:CreateChangeSet",
					"cloudformation:DescribeChangeSet",
					"cloudformation:DescribeStackResource",
					"cloudformation:DescribeStacks",
					"cloudformation:ExecuteChangeSet",
					"ec2:DescribeSecurityGroups",
					"ec2:DescribeSubnets",
					"ec2:DescribeVpcs",
					"kms:DescribeKey",
					"kms:ListAliases",
					"kms:ListKeys",
					"lambda:ListFunctions",
					"rds:DescribeDBClusters",
					"rds:DescribeDBInstances",
					"redshift:DescribeClusters",
					"tag:GetResources",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Sid:    "LambdaPermissions",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"lambda:AddPermission",
					"lambda:CreateFunction",
					"lambda:GetFunction",
					"lambda:InvokeFunction",
					"lambda:UpdateFunctionConfiguration",
				},
				Resource: StringOrSlice{"arn:aws:lambda:*:*:function:SecretsManager*"},
			},
			{
				Sid:      "SARPermissions",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"serverlessrepo:CreateCloudFormationChangeSet", "serverlessrepo:GetApplication"},
				Resource: StringOrSlice{"arn:aws:serverlessrepo:*:*:applications/SecretsManager*"},
			},
			{
				Sid:    "S3Permissions",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{"s3:GetObject"},
				Resource: StringOrSlice{
					"arn:aws:s3:::awsserverlessrepo-changesets*",
					"arn:aws:s3:::secrets-manager-rotation-apps-*/*",
				},
			},
		}}),

	mp("AmazonSSMFullAccess", "ANPAI4JB77JXPKNVOJEAZ",
		"Provides full access to Amazon SSM.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"cloudwatch:PutMetricData",
					"ds:CreateComputer",
					"ds:DescribeDirectories",
					"ec2:DescribeInstanceStatus",
					"logs:*",
					"ssm:*",
					"ec2messages:*",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:CreateServiceLinkedRole"},
				Resource: StringOrSlice{"arn:aws:iam::*:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringLike": {"iam:AWSServiceName": {"ssm.amazonaws.com"}},
				},
			},
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{"iam:DeleteServiceLinkedRole", "iam:GetServiceLinkedRoleDeletionStatus"},
				Resource: StringOrSlice{
					"arn:aws:iam::*:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM*",
				},
			},
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"ssmmessages:CreateControlChannel",
					"ssmmessages:CreateDataChannel",
					"ssmmessages:OpenControlChannel",
					"ssmmessages:OpenDataChannel",
				},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("AmazonSSMReadOnlyAccess", "ANPAI4JB77JXPKNVOJEB1",
		"Provides read only access to Amazon SSM.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"ssm:Describe*", "ssm:Get*", "ssm:List*"},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("AWSCodeBuildDeveloperAccess", "ANPAI4JB77JXPKNVOJECB",
		"Provides access to AWS CodeBuild via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Sid:    "AWSServicesAccess",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"codebuild:StartBuild",
					"codebuild:StopBuild",
					"codebuild:StartBuildBatch",
					"codebuild:StopBuildBatch",
					"codebuild:RetryBuild",
					"codebuild:RetryBuildBatch",
					"codebuild:BatchGet*",
					"codebuild:GetResourcePolicy",
					"codebuild:DescribeTestCases",
					"codebuild:DescribeCodeCoverages",
					"codebuild:List*",
					"codecommit:GetBranch",
					"codecommit:GetCommit",
					"codecommit:GetRepository",
					"codecommit:ListBranches",
					"cloudwatch:GetMetricStatistics",
					"events:DescribeRule",
					"events:ListTargetsByRule",
					"events:ListRuleNamesByTarget",
					"logs:GetLogEvents",
					"s3:GetBucketLocation",
					"s3:ListAllMyBuckets",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Sid:      "SSMParameterWriteAccess",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"ssm:PutParameter"},
				Resource: StringOrSlice{"arn:aws:ssm:*:*:parameter/CodeBuild/*"},
			},
			{
				Sid:    "CodeStarNotificationsReadWriteAccess",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"codestar-notifications:CreateNotificationRule",
					"codestar-notifications:DescribeNotificationRule",
					"codestar-notifications:UpdateNotificationRule",
					"codestar-notifications:Subscribe",
					"codestar-notifications:Unsubscribe",
				},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"ArnLike": {
						"codestar-notifications:NotificationsForResource": {"arn:aws:codebuild:*:*:project/*"},
					},
				},
			},
			{
				Sid:    "CodeStarNotificationsListAccess",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"codestar-notifications:ListNotificationRules",
					"codestar-notifications:ListEventTypes",
					"codestar-notifications:ListTargets",
					"codestar-notifications:ListTagsforResource",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Sid:      "SNSTopicListAccess",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"sns:ListTopics", "sns:GetTopicAttributes"},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("AWSCodeBuildReadOnlyAccess", "ANPAI4JB77JXPKNVOJECC",
		"Provides read only access to AWS CodeBuild via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Sid:    "AWSServicesAccess",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"codebuild:BatchGet*",
					"codebuild:GetResourcePolicy",
					"codebuild:List*",
					"codebuild:DescribeTestCases",
					"codebuild:DescribeCodeCoverages",
					"codecommit:GetBranch",
					"codecommit:GetCommit",
					"codecommit:GetRepository",
					"cloudwatch:GetMetricStatistics",
					"events:DescribeRule",
					"events:ListTargetsByRule",
					"events:ListRuleNamesByTarget",
					"logs:GetLogEvents",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Sid:      "CodeStarNotificationsPowerUserAccess",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"codestar-notifications:DescribeNotificationRule"},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"ArnLike": {
						"codestar-notifications:NotificationsForResource": {"arn:aws:codebuild:*:*:project/*"},
					},
				},
			},
			{
				Sid:    "CodeStarNotificationsListAccess",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"codestar-notifications:ListNotificationRules",
					"codestar-notifications:ListEventTypes",
					"codestar-notifications:ListTargets",
				},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("AWSCodeDeployFullAccess", "ANPAI4JB77JXPKNVOJECD",
		"Provides full access to CodeDeploy resources.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{Effect: IAMEffectAllow, Action: StringOrSlice{"codedeploy:*"}, Resource: StringOrSlice{"*"}},
			{
				Sid:    "CodeStarNotificationsReadWriteAccess",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"codestar-notifications:CreateNotificationRule",
					"codestar-notifications:DescribeNotificationRule",
					"codestar-notifications:UpdateNotificationRule",
					"codestar-notifications:DeleteNotificationRule",
					"codestar-notifications:Subscribe",
					"codestar-notifications:Unsubscribe",
				},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"ArnLike": {
						"codestar-notifications:NotificationsForResource": {"arn:aws:codedeploy:*:*:application:*"},
					},
				},
			},
			{
				Sid:    "CodeStarNotificationsListAccess",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"codestar-notifications:ListNotificationRules",
					"codestar-notifications:ListTargets",
					"codestar-notifications:ListTagsforResource",
					"codestar-notifications:ListEventTypes",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Sid:      "CodeStarNotificationsSNSTopicCreateAccess",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"sns:CreateTopic", "sns:SetTopicAttributes"},
				Resource: StringOrSlice{"arn:aws:sns:*:*:codestar-notifications*"},
			},
			{
				Sid:      "SNSTopicListAccess",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"sns:ListTopics"},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("AWSCodeDeployReadOnlyAccess", "ANPAI4JB77JXPKNVOJECE",
		"Provides read only access to CodeDeploy resources.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"codedeploy:Batch*", "codedeploy:Get*", "codedeploy:List*"},
				Resource: StringOrSlice{"*"},
			},
			{
				Sid:      "CodeStarNotificationsPowerUserAccess",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"codestar-notifications:DescribeNotificationRule"},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"ArnLike": {
						"codestar-notifications:NotificationsForResource": {"arn:aws:codedeploy:*:*:application:*"},
					},
				},
			},
			{
				Sid:    "CodeStarNotificationsListAccess",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"codestar-notifications:ListNotificationRules",
					"codestar-notifications:ListEventTypes",
					"codestar-notifications:ListTargets",
				},
				Resource: StringOrSlice{"*"},
			},
		}}),

	mp("AWSCodePipeline_FullAccess", "ANPAI4JB77JXPKNVOJECF",
		"Provides full access to AWS CodePipeline via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Sid:    "CodePipelineAuthoringAccess",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"codepipeline:*",
					"cloudformation:DescribeStacks",
					"cloudformation:ListStacks",
					"cloudformation:ListChangeSets",
					"codebuild:BatchGetProjects",
					"codebuild:CreateProject",
					"codebuild:ListCuratedEnvironmentImages",
					"codebuild:ListProjects",
					"codecommit:ListBranches",
					"codecommit:GetReferences",
					"codecommit:ListRepositories",
					"codedeploy:BatchGetDeploymentGroups",
					"codedeploy:ListApplications",
					"codedeploy:ListDeploymentGroups",
					"ec2:DescribeSecurityGroups",
					"ec2:DescribeSubnets",
					"ec2:DescribeVpcs",
					"ecr:DescribeRepositories",
					"ecr:ListImages",
					"ecs:ListClusters",
					"ecs:ListServices",
					"elasticbeanstalk:DescribeApplications",
					"elasticbeanstalk:DescribeEnvironments",
					"iam:ListRoles",
					"iam:GetRole",
					"lambda:ListFunctions",
					"events:ListRules",
					"events:ListTargetsByRule",
					"events:DescribeRule",
					"s3:ListAllMyBuckets",
					"sns:ListTopics",
					"codestar-notifications:ListNotificationRules",
					"codestar-notifications:ListTargets",
					"codestar-notifications:ListTagsforResource",
					"codestar-notifications:ListEventTypes",
					"states:ListStateMachines",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Sid:    "CodePipelineArtifactsReadWriteAccess",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"s3:GetObject",
					"s3:ListBucket",
					"s3:GetBucketPolicy",
					"s3:GetBucketVersioning",
					"s3:GetObjectVersion",
					"s3:CreateBucket",
					"s3:PutBucketPolicy",
				},
				Resource: StringOrSlice{"arn:aws:s3::*:codepipeline-*"},
			},
			{
				Sid:      "EventsIAMPassRole",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:PassRole"},
				Resource: StringOrSlice{"arn:aws:iam::*:role/service-role/cwe-role-*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringEquals": {"iam:PassedToService": {"events.amazonaws.com"}},
				},
			},
			{
				Sid:      "CodePipelineIAMPassRole",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:PassRole"},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringEquals": {"iam:PassedToService": {"codepipeline.amazonaws.com"}},
				},
			},
			{
				Sid:    "CodePipelineEventsReadWriteAccess",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"events:PutRule",
					"events:PutTargets",
					"events:DeleteRule",
					"events:DisableRule",
					"events:RemoveTargets",
				},
				Resource: StringOrSlice{"arn:aws:events:*:*:rule/codepipeline-*"},
			},
			{
				Sid:    "CodeStarNotificationsReadWriteAccess",
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"codestar-notifications:CreateNotificationRule",
					"codestar-notifications:DescribeNotificationRule",
					"codestar-notifications:UpdateNotificationRule",
					"codestar-notifications:DeleteNotificationRule",
					"codestar-notifications:Subscribe",
					"codestar-notifications:Unsubscribe",
				},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringLike": {
						"codestar-notifications:NotificationsForResource": {"arn:aws:codepipeline:*"},
					},
				},
			},
			{
				Sid:      "CodeStarNotificationsSNSTopicCreateAccess",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"sns:CreateTopic", "sns:SetTopicAttributes"},
				Resource: StringOrSlice{"arn:aws:sns:*:*:codestar-notifications*"},
			},
		}}),

	mp("AWSCodePipeline_ReadOnlyAccess", "ANPAI4JB77JXPKNVOJECG",
		"Provides read only access to AWS CodePipeline via the AWS Management Console.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"codepipeline:GetPipeline",
					"codepipeline:GetPipelineState",
					"codepipeline:GetPipelineExecution",
					"codepipeline:ListPipelineExecutions",
					"codepipeline:ListActionExecutions",
					"codepipeline:ListActionTypes",
					"codepipeline:ListPipelines",
					"codepipeline:ListTagsForResource",
					"s3:ListAllMyBuckets",
					"codestar-notifications:ListNotificationRules",
					"codestar-notifications:ListEventTypes",
					"codestar-notifications:ListTargets",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"s3:GetObject", "s3:ListBucket", "s3:GetBucketPolicy"},
				Resource: StringOrSlice{"arn:aws:s3::*:codepipeline-*"},
			},
			{
				Sid:      "CodeStarNotificationsReadOnlyAccess",
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"codestar-notifications:DescribeNotificationRule"},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringLike": {
						"codestar-notifications:NotificationsForResource": {"arn:aws:codepipeline:*"},
					},
				},
			},
		}}),

	mp("AmazonCognitoPowerUser", "ANPAI4JB77JXPKNVOJECJ",
		"Provides administrative access to existing Amazon Cognito resources.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"cognito-identity:*",
					"cognito-idp:*",
					"cognito-sync:*",
					"iam:ListRoles",
					"iam:ListOpenIdConnectProviders",
					"iam:GetRole",
					"iam:ListSAMLProviders",
					"iam:GetSAMLProvider",
					"kinesis:ListStreams",
					"lambda:GetPolicy",
					"lambda:ListFunctions",
					"sns:GetSMSSandboxAccountStatus",
					"sns:ListPlatformApplications",
					"ses:ListIdentities",
					"ses:GetIdentityVerificationAttributes",
					"mobiletargeting:GetApps",
					"acm:ListCertificates",
					"sms-voice:DescribeAccountAttributes",
				},
				Resource: StringOrSlice{"*"},
			},
			{
				Effect:   IAMEffectAllow,
				Action:   StringOrSlice{"iam:CreateServiceLinkedRole"},
				Resource: StringOrSlice{"*"},
				Condition: map[string]map[string]StringOrSlice{
					"StringEquals": {
						"iam:AWSServiceName": {
							"cognito-idp.amazonaws.com",
							"email.cognito-idp.amazonaws.com",
						},
					},
				},
			},
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{"iam:DeleteServiceLinkedRole", "iam:GetServiceLinkedRoleDeletionStatus"},
				Resource: StringOrSlice{
					"arn:aws:iam::*:role/aws-service-role/cognito-idp.amazonaws.com/AWSServiceRoleForAmazonCognitoIdp*",
					"arn:aws:iam::*:role/aws-service-role/email.cognito-idp.amazonaws.com/AWSServiceRoleForAmazonCognitoIdpEmail*",
				},
			},
		}}),

	mp("AmazonCognitoReadOnly", "ANPAI4JB77JXPKNVOJECW",
		"Provides read only access to Amazon Cognito resources.",
		PolicyDocument{Version: "2012-10-17", Statement: []PolicyStatement{
			{
				Effect: IAMEffectAllow,
				Action: StringOrSlice{
					"cognito-identity:Describe*",
					"cognito-identity:Get*",
					"cognito-identity:List*",
					"cognito-idp:Describe*",
					"cognito-idp:AdminGet*",
					"cognito-idp:AdminList*",
					"cognito-idp:List*",
					"cognito-idp:Get*",
					"cognito-sync:Describe*",
					"cognito-sync:Get*",
					"cognito-sync:List*",
					"iam:ListOpenIdConnectProviders",
					"iam:ListRoles",
					"sns:ListPlatformApplications",
				},
				Resource: StringOrSlice{"*"},
			},
		}}),
}

// mp is a helper for constructing a bundled managed IAMPolicy.
func mp(name, id, description string, doc PolicyDocument) *IAMPolicy {
	return &IAMPolicy{
		PolicyName:       name,
		PolicyID:         id,
		ARN:              "arn:aws:iam::aws:policy/" + name,
		Path:             "/",
		Description:      description,
		DefaultVersionID: "v1",
		IsAttachable:     true,
		CreateDate:       managedPolicyDate,
		UpdateDate:       managedPolicyDate,
		Document:         doc,
	}
}

var (
	managedPolicyOnce sync.Once
	managedPolicyMap  map[string]*IAMPolicy
)

func initManagedPolicyMap() {
	managedPolicyMap = make(map[string]*IAMPolicy, len(managedPolicies))
	for _, p := range managedPolicies {
		managedPolicyMap[p.ARN] = p
	}
}

// ListManagedPolicies returns all 47 bundled AWS managed policies.
func ListManagedPolicies() []*IAMPolicy {
	return managedPolicies
}

// GetManagedPolicy returns the managed policy with the given ARN, or false
// if no such policy exists in the bundled set.
func GetManagedPolicy(arn string) (*IAMPolicy, bool) {
	managedPolicyOnce.Do(initManagedPolicyMap)
	p, ok := managedPolicyMap[arn]
	return p, ok
}
