package substrate

import (
	"bytes"
	"fmt"
	"go/format"
	"net/http"
	"strings"
	"text/template"
)

// fixtureEvent holds the per-event data for the generated test template.
type fixtureEvent struct {
	Sequence   int64
	Service    string
	Operation  string
	Method     string
	Path       string
	Host       string
	BodyLit    string
	StatusCode int
}

var fixtureTemplate = template.Must(template.New("fixture").Parse(`package {{.Package}}

import (
	"net/http"
	"strings"
	"testing"

	"github.com/scttfrdmn/substrate"
)

// {{.TestName}} replays {{.EventCount}} recorded AWS API request(s) against a
// fresh Substrate server. It was generated by the Substrate debug UI export
// feature and can be copied into any test file in the repository.
func {{.TestName}}(t *testing.T) {
	t.Helper()
	srv := substrate.StartTestServer(t)
{{range .Events}}
	// seq={{.Sequence}} {{.Service}}/{{.Operation}}
	{
		req, err := http.NewRequest({{printf "%q" .Method}}, srv.URL+{{printf "%q" .Path}}, {{.BodyLit}})
		if err != nil {
			t.Fatal(err)
		}
		{{- if .Host}}
		req.Host = {{printf "%q" .Host}}
		{{- end}}
		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			t.Fatal(err)
		}
		resp.Body.Close()
		if resp.StatusCode != {{.StatusCode}} {
			t.Errorf("seq {{.Sequence}} ({{.Service}}/{{.Operation}}): want status %d, got %d", {{.StatusCode}}, resp.StatusCode)
		}
	}
{{end}}}
`))

// GenerateTestFixture generates a Go test file from a slice of recorded events.
// It returns the gofmt-formatted source of a *_test.go file that replays the
// recorded requests against a fresh Substrate test server started via
// [StartTestServer]. Only events that have a stored Request are included;
// events without request bodies are silently skipped.
func GenerateTestFixture(events []*Event, packageName, testName string) (string, error) {
	var evData []fixtureEvent
	for _, ev := range events {
		if ev.Request == nil {
			continue
		}

		method := http.MethodPost
		if m, ok := ev.Request.Headers[":method"]; ok && m != "" {
			method = m
		} else if m2, ok2 := ev.Request.Headers["Method"]; ok2 && m2 != "" {
			method = m2
		}

		path := ev.Request.Path
		if path == "" {
			path = "/"
		}

		host := ""
		if ev.Request.Headers != nil {
			host = ev.Request.Headers["Host"]
		}

		statusCode := http.StatusOK
		if ev.Response != nil && ev.Response.StatusCode != 0 {
			statusCode = ev.Response.StatusCode
		}

		bodyLit := bodyLiteral(ev.Request.Body)

		evData = append(evData, fixtureEvent{
			Sequence:   ev.Sequence,
			Service:    ev.Service,
			Operation:  ev.Operation,
			Method:     method,
			Path:       path,
			Host:       host,
			BodyLit:    bodyLit,
			StatusCode: statusCode,
		})
	}

	type tmplData struct {
		Package    string
		TestName   string
		EventCount int
		Events     []fixtureEvent
	}

	var buf bytes.Buffer
	if err := fixtureTemplate.Execute(&buf, tmplData{
		Package:    packageName,
		TestName:   testName,
		EventCount: len(evData),
		Events:     evData,
	}); err != nil {
		return "", fmt.Errorf("execute fixture template: %w", err)
	}

	// Remove unused import if no events have bodies that use strings.NewReader.
	src := buf.String()
	if !strings.Contains(src, "strings.NewReader") {
		src = strings.Replace(src, "\t\"strings\"\n", "", 1)
	}

	formatted, err := format.Source([]byte(src))
	if err != nil {
		// Return unformatted source if gofmt fails (e.g. invalid identifier).
		return src, nil //nolint:nilerr
	}
	return string(formatted), nil
}

// bodyLiteral returns a Go expression for the request body:
//   - "http.NoBody" when body is empty
//   - "strings.NewReader(`…`)" for bodies without backticks
//   - fmt.Sprintf("strings.NewReader(%q)", …) when the body contains a backtick
func bodyLiteral(body []byte) string {
	if len(body) == 0 {
		return "http.NoBody"
	}
	s := string(body)
	if strings.ContainsRune(s, '`') {
		return fmt.Sprintf("strings.NewReader(%q)", s)
	}
	return "strings.NewReader(`" + s + "`)"
}
