package emulator

import "net/http"

// Athena pages two listings by an array offset, and a token it never issued is refused (#1086).
//
// ListQueryExecutions and ListWorkGroups both decoded their NextToken with the pre-#915 idiom —
// base64.StdEncoding.DecodeString then strconv.Atoi, both errors discarded — so a token substrate
// could not have issued left the offset at zero and the operation answered a well-formed **page
// one**. That is the one wrong answer a paginating caller cannot detect: a loop that runs until the
// token comes back empty is handed the first page again, so it either spins or processes the same
// records twice, and nothing in the response says so. Both now share [decodeOffsetPaginationToken],
// which defines issuability as a round trip through the encoder, and [pageByOffsetToken], which was
// already the cut both had written out by hand.
//
// # What the pages publish, and what is substrate's reading
//
// Athena is the best-documented of #1086's sites, because its NextToken description says where a
// token comes from: *"A token generated by the Athena service that specifies where to continue
// pagination if a previous request was truncated. To obtain the next set of pages, pass in the
// NextToken from the response object of the previous page call."* — published verbatim on both
// operations, for the request parameter and again for the response element. A token no previous
// response carried is therefore not the thing the parameter is documented to accept, which is a
// stronger footing than the other sites in this class have.
//
// The code is [athenaInvalidPaginationToken]'s InvalidRequestException/400, published in **both**
// operations' own Errors sections and glossed *"Indicates that something is wrong with the input to
// the request. For example, a required parameter may be missing or out of range."* — so it is this
// operation's own vocabulary and not one borrowed from a sibling, which is what [#671]'s scope
// decision requires. It is already this plugin's code for a malformed input at five other doors.
//
// What remains substrate's reading is only that this particular input problem is the one that gloss
// covers: neither page publishes a code AWS attributes to a pagination token, and Athena's
// common-errors page carries nothing about one either.
//
// The published Length constraint on NextToken — minimum 1, maximum 1024 on both the request and the
// response — needs no check of its own. The encoder emits an offset in decimal base64, a handful of
// characters, so every token longer than 1024 already fails the round trip; and the minimum of 1 is
// why an empty NextToken is an *absent* token, the start of the listing, rather than an invalid one.
//
// # Ordering
//
// The token is decoded before any state is read, which is #887's criterion: a refusal must not depend
// on how much state happens to exist, and a store failure must not be reported as a 500 for a request
// that was already refusable. Neither operation resolves a resource first, so neither has a NotFound
// whose precedence has to be preserved — ListQueryExecutions' WorkGroup is a filter, not a lookup, and
// an absent workgroup yields an empty list rather than a refusal.
//
// That ordering cannot be asserted by sealing the store the way #915's other sites are, because
// [athenaLoadStringIndex] reports a store failure as an empty index: a sealed read answers 200 with
// an empty page, indistinguishable from an empty listing, so the seal would pass whichever side of
// the read the decode sat on. The test counts reads instead and requires the refused request to have
// performed none — see TestPaginationToken_AthenaListQueryExecutionsRefusesATokenItDidNotIssue.
//
// # Not fixed here, so that the conversion is not read as having fixed it
//
// Both operations take a caller-supplied MaxResults whose published Valid Range is 0–50 for
// ListQueryExecutions and 1–50 for ListWorkGroups. Substrate accepts a value above the maximum and
// silently rewrites one at or below zero to [athenaListDefaultPageSize]; that is the unenforced
// page-size class, a separate defect from the token, and it is left exactly as it was.
//
// [#671]: https://github.com/scttfrdmn/substrate/issues/671

// athenaListDefaultPageSize is the page size both listings apply when MaxResults is absent.
//
// Neither page publishes a default, so this is substrate's choice and not a verified figure. It is the
// published *maximum* of both operations' Valid Range, which is the most a caller can ask for and so
// the largest page an unbounded request could legitimately receive. Named rather than repeated as a
// literal so that the unverified part of the page size is visible at both sites.
const athenaListDefaultPageSize = 50

// athenaInvalidPaginationToken refuses a NextToken that no previous call to operation returned.
//
// The operation name is in the message because a token from the *other* Athena listing is one of the
// ways a caller arrives here: both encode an offset the same way, so ListWorkGroups' token decodes
// cleanly under ListQueryExecutions and would otherwise index into the wrong listing. The published
// gloss is not restated, because a caller told that something is wrong with its input cannot tell
// which parameter AWS means, and NextToken is the only one this refusal can be about.
func athenaInvalidPaginationToken(operation string) *AWSError {
	return &AWSError{
		Code:       "InvalidRequestException",
		Message:    "NextToken is not a token returned by a previous " + operation + " request",
		HTTPStatus: http.StatusBadRequest,
	}
}
