package emulator

// This file is the reader for the generated authorization reference table
// (authz_reference_gen.go). The table is AWS's own Service Reference Information,
// vendored under emulator/authzref and regenerated by cmd/gen-authz-reference; nothing
// here should read either map directly, so that the meaning of an absent key stays in one
// place.
//
// Why substrate needs it at all: a request's resource is not a property of the request
// alone. AWS documents, per action, which resource types the action supports, and an
// action supporting none is authorized against `*` no matter what identifiers the request
// carries. Substrate derived resources from parameters without consulting that table,
// which made a policy scoping `ec2:DescribeInstances` to an instance ARN grant those
// instances here and nothing on AWS (#762). The table is how a per-operation resource
// derivation can be checked against AWS's published answer rather than argued about.

// authzActionResourceTypes returns the resource types AWS publishes for an action, and
// whether AWS publishes the action at all.
//
// The two returns are different facts and callers need both. `ok` false means the action
// is absent from AWS's reference — substrate's own invention, a rename, or a snapshot
// older than the API. `ok` true with an empty slice means AWS publishes the action and
// documents no resource type for it, which is how the reference says "no resource-level
// permissions": a real request's resource is then `*`.
func authzActionResourceTypes(service, operation string) ([]string, bool) {
	types, ok := authzActionResources[service+":"+operation]
	return types, ok
}

// authzActionSupportsResourceType reports whether AWS documents resourceType as one of
// the types the given action supports.
//
// False for an action AWS scopes to `*`, and false for an action substrate names but AWS
// does not publish. Both answers point the same way — authorize against `*` — because a
// resource narrower than the one AWS would use is a grant substrate would be inventing,
// and inventing a grant is worse than inventing a refusal: the caller's test passes here
// and the deployment fails there.
func authzActionSupportsResourceType(service, operation, resourceType string) bool {
	types, ok := authzActionResourceTypes(service, operation)
	if !ok {
		return false
	}
	for _, t := range types {
		if t == resourceType {
			return true
		}
	}
	return false
}

// authzResourceARNFormats returns the ARN formats AWS documents for a resource type, in
// AWS's own ${Placeholder} notation, and whether the type is published at all.
//
// It is not used to build an ARN — the placeholders are prose, not a template substrate
// fills in — but to check the ARNs substrate does build against the shape AWS publishes,
// so that a resolver and its citation cannot drift apart silently.
func authzResourceARNFormats(service, resourceType string) ([]string, bool) {
	formats, ok := authzResourceARNFormatsByType[service+":"+resourceType]
	return formats, ok
}
