package emulator

import "slices"

// The exported read side of the operation catalog (#1095).
//
// Until this existed, the set of operations a plugin routes lived only as `case` labels in
// its HandleRequest switch: [Plugin] exposes Name, Initialize, Shutdown and HandleRequest
// and nothing else, and [PluginRouting] carries the routing predicates rather than an
// operation list. So the only way to enumerate what substrate routes was to grep Go source,
// which is how two careful counts of the same tree came to disagree by five, and why the
// drift check #1015 asks for — fail when a routed operation has no documentation row —
// could not be written at all.
//
// The catalog is exported as package functions rather than as an Operations method on
// [Plugin] for two reasons. A method on the interface would break every out-of-tree
// implementation, which examples/custom_plugin exists to document; and it would hold the
// list *beside* the switch, where it can drift from the router, when the whole point is
// that it is derived *from* the switch. The data these read is generated by
// cmd/gen-operation-catalog and checked by `make operation-catalog-check`; that command's
// doc comment records the alternatives and why each was rejected.
//
// Both functions return copies, so a caller cannot reach the generated table through them.

// RoutedServices returns the names of every plugin in the operation catalog, sorted.
//
// These are registration names — "ec2", "apigateway-proxy" — the same vocabulary
// [PluginRegistry.Names] and emulator/routing.go use, not Go type names.
func RoutedServices() []string {
	names := make([]string, 0, len(routedOperations))
	for name := range routedOperations {
		names = append(names, name)
	}
	slices.Sort(names)
	return names
}

// RoutedOperations returns the operations the named plugin routes, sorted, or nil if no
// plugin is registered under that name.
//
// An empty, non-nil result is a plugin that routes no operation *names*: substrate has two,
// apigateway-proxy and opensearch, both of which dispatch on an HTTP method and a path
// shape because their protocols carry no operation name for them to route. The generated
// table records the reason at each of those entries, and the generator refuses to emit an
// empty entry for any other plugin, so a short list is a build failure rather than a quiet
// undercount. A caller that needs to tell "routes nothing" from "is not a plugin" therefore
// has to test for nil rather than for length.
func RoutedOperations(service string) []string {
	ops, ok := routedOperations[service]
	if !ok {
		return nil
	}
	return slices.Clone(ops)
}
