package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestPrune_SortsEveryListSoARefreshIsAByteStableDiff asserts the property the vendored
// snapshots depend on: AWS serves actions and resource types in no documented order, so a
// refresh that changed nothing would still produce a large diff unless the tool sorts. A
// noisy diff is a review nobody performs.
func TestPrune_SortsEveryListSoARefreshIsAByteStableDiff(t *testing.T) {
	svc := prune(rawService{
		Name: "ec2", Version: "v1.4",
		Actions: []rawAction{
			{Name: "TerminateInstances", Resources: []rawActionTarget{{Name: "volume"}, {Name: "instance"}}},
			{Name: "DescribeInstances"},
		},
		Resources: []rawResource{
			{Name: "volume", ARNFormats: []string{"b", "a"}},
			{Name: "instance", ARNFormats: []string{"arn:instance"}},
		},
	})

	if svc.Name != "ec2" || svc.Version != "v1.4" {
		t.Fatalf("prune dropped identity: %+v", svc)
	}
	if got := []string{svc.Actions[0].Name, svc.Actions[1].Name}; got[0] != "DescribeInstances" || got[1] != "TerminateInstances" {
		t.Errorf("actions not sorted: %v", got)
	}
	if got := svc.Actions[1].Resources; len(got) != 2 || got[0] != "instance" || got[1] != "volume" {
		t.Errorf("action resource types not sorted: %v", got)
	}
	// An action AWS publishes with no resource types must survive pruning as an empty,
	// non-nil list: that is how the reference says "no resource-level permissions", and it
	// is the distinction #762 turns on.
	if got := svc.Actions[0].Resources; got == nil || len(got) != 0 {
		t.Errorf("an action with no resource types pruned to %#v, want an empty list", got)
	}
	if got := []string{svc.Resources[0].Name, svc.Resources[1].Name}; got[0] != "instance" || got[1] != "volume" {
		t.Errorf("resource types not sorted: %v", got)
	}
	if got := svc.Resources[1].ARNFormats; got[0] != "a" || got[1] != "b" {
		t.Errorf("ARN formats not sorted: %v", got)
	}
}

// TestWriteEntry_WrapsOnlyWhatWouldBeUnreadable checks both arms of the wrapping rule. Two
// EC2 rows — CreateTags and DeleteTags — name over a hundred resource types each, and left
// on one line they are the only unreviewable part of the generated file.
func TestWriteEntry_WrapsOnlyWhatWouldBeUnreadable(t *testing.T) {
	tests := []struct {
		name   string
		key    string
		values []string
		want   string
	}{
		{
			name: "an action with no resource types", key: "ec2:DescribeInstances",
			want: "\t\"ec2:DescribeInstances\": {},\n",
		},
		{
			name: "a short entry stays on one line", key: "ec2:TerminateInstances",
			values: []string{"instance"},
			want:   "\t\"ec2:TerminateInstances\": {\"instance\"},\n",
		},
		{
			name: "a long entry is one element per line", key: "ec2:CreateTags",
			values: []string{
				"capacity-reservation", "carrier-gateway", "client-vpn-endpoint",
				"customer-gateway",
			},
			want: "\t\"ec2:CreateTags\": {\n" +
				"\t\t\"capacity-reservation\",\n" +
				"\t\t\"carrier-gateway\",\n" +
				"\t\t\"client-vpn-endpoint\",\n" +
				"\t\t\"customer-gateway\",\n" +
				"\t},\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var b bytes.Buffer
			writeEntry(&b, tt.key, tt.values)
			if got := b.String(); got != tt.want {
				t.Errorf("writeEntry wrote\n%q\nwant\n%q", got, tt.want)
			}
		})
	}
}

// TestRender_ProducesCompilableSourceCitingItsSnapshot asserts render's output is valid Go
// — it runs the loaded table through go/format, which parses — and that the header names
// where the data came from and at which version. The header is the citation every row of
// both maps rests on; without it the file is an assertion about AWS with no source.
func TestRender_ProducesCompilableSourceCitingItsSnapshot(t *testing.T) {
	svcs := []service{{
		Name: "iam", Version: "v1.4",
		Actions: []action{
			{Name: "GetUser", Resources: []string{"user"}},
			{Name: "ListUsers", Resources: []string{}},
		},
		Resources: []resource{
			{Name: "user", ARNFormats: []string{"arn:${Partition}:iam::${Account}:user/${UserNameWithPath}"}},
		},
	}}

	out, err := render(svcs)
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	got := string(out)

	for _, want := range []string{
		"// Code generated by cmd/gen-authz-reference; DO NOT EDIT.",
		"https://servicereference.us-east-1.amazonaws.com/",
		"iam  v1.4    2 actions,   1 resource types",
		"package emulator",
		"var authzActionResources = map[string][]string{",
		// gofmt aligns the values within a map literal, so the assertion cannot assume
		// exactly one space after the colon.
		"\"iam:GetUser\":   {\"user\"},",
		"\"iam:ListUsers\": {},",
		"var authzResourceARNFormatsByType = map[string][]string{",
		"\"iam:user\": {\"arn:${Partition}:iam::${Account}:user/${UserNameWithPath}\"},",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("generated source is missing %q", want)
		}
	}
}

// TestLoad_RefusesASnapshotItCannotTrust covers the four ways the vendored data can be
// wrong. Each refusal exists because the alternative is silent: a missing or truncated
// snapshot would generate a table that classifies every action as unpublished, which the
// #762 gate reads as "authorize against *" — a behavior change disguised as data.
func TestLoad_RefusesASnapshotItCannotTrust(t *testing.T) {
	tests := []struct {
		name    string
		write   map[string]string
		wantErr string
	}{
		{
			name:    "a snapshot that is not there",
			write:   map[string]string{},
			wantErr: "make authz-reference-fetch",
		},
		{
			name:    "a snapshot that is not JSON",
			write:   map[string]string{"ec2.json": "{", "iam.json": "{"},
			wantErr: "parse",
		},
		{
			name: "a snapshot naming another service",
			write: map[string]string{
				"ec2.json": `{"Name":"ecs","Version":"v1.4","Actions":[{"Name":"X"}]}`,
				"iam.json": `{"Name":"iam","Version":"v1.4","Actions":[{"Name":"X"}]}`,
			},
			wantErr: `names service "ecs"`,
		},
		{
			name: "a snapshot with no actions",
			write: map[string]string{
				"ec2.json": `{"Name":"ec2","Version":"v1.4","Actions":[]}`,
				"iam.json": `{"Name":"iam","Version":"v1.4","Actions":[{"Name":"X"}]}`,
			},
			wantErr: "lists no actions",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			for name, body := range tt.write {
				if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o600); err != nil {
					t.Fatalf("write %s: %v", name, err)
				}
			}
			_, err := load(dir)
			if err == nil {
				t.Fatalf("load accepted %s", tt.name)
			}
			if !strings.Contains(err.Error(), tt.wantErr) {
				t.Errorf("load error is %q, want it to mention %q", err, tt.wantErr)
			}
		})
	}
}

// TestLoad_ReadsTheCommittedSnapshots is the check the -check flag performs, exercised
// against the data actually in the repository: both services load, both carry the actions
// the authorization gates read, and both are at the version the generated header claims.
func TestLoad_ReadsTheCommittedSnapshots(t *testing.T) {
	svcs, err := load(filepath.Join("..", "..", "emulator", "authzref"))
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	if len(svcs) != len(services) {
		t.Fatalf("loaded %d services, want %d", len(svcs), len(services))
	}
	for _, svc := range svcs {
		if svc.Version == "" {
			t.Errorf("%s: snapshot records no Version, so the generated header cannot cite one", svc.Name)
		}
		if len(svc.Resources) == 0 {
			t.Errorf("%s: snapshot lists no resource types, so no ARN format can be cited", svc.Name)
		}
	}
}
