// Command gen-service-reference keeps the coverage matrix in docs/services.md in
// sync with the live plugin registry so the documented service count and plugin
// list can never drift from the implementation (see issue #364).
//
// It boots the default plugin registry, enumerates the registered plugins, and
// renders a Markdown coverage table between the marker comments
//
//	<!-- BEGIN GENERATED COVERAGE MATRIX -->
//	<!-- END GENERATED COVERAGE MATRIX -->
//
// in docs/services.md. Everything outside the markers — including the
// hand-written per-service operation, CloudFormation, and cost detail — is left
// untouched. Per-plugin display names and protocols come from the emulator's own
// routing table ([emu.PluginRoutingCatalog], emulator/routing.go); the tool fails
// if a registered plugin has no entry there (or an entry names a plugin that is
// not registered), which is what a CI drift check enforces.
//
// The per-plugin routed-operation count in the matrix comes from the operation
// catalog ([emu.RoutedOperations], generated by cmd/gen-operation-catalog from each
// plugin's dispatch switch), so the documented count is a projection of the router
// and not a figure anyone maintains by hand — two careful hand counts of the same
// tree disagreed by five, which is what #1095 exists to end. The catalog is checked
// against the registry in both directions here too, so a plugin the catalog does not
// cover fails this tool rather than rendering a silent zero.
//
// Usage:
//
//	go run ./cmd/gen-service-reference -out docs/services.md          # rewrite the matrix
//	go run ./cmd/gen-service-reference -out docs/services.md -check    # exit non-zero if out of date
package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"log/slog"
	"os"
	"sort"
	"time"

	emu "github.com/scttfrdmn/substrate/emulator"
)

const (
	beginMarker = "<!-- BEGIN GENERATED COVERAGE MATRIX -->"
	endMarker   = "<!-- END GENERATED COVERAGE MATRIX -->"
)

// routing is the per-plugin routing and documentation metadata, read from the
// emulator's own table (emulator/routing.go) rather than kept in a second copy
// here. One table then serves three consumers: this matrix, the drift check
// below, and the reachability sweep test that asserts every identifier in it
// resolves to a registered plugin (#739). A duplicate map in cmd/ could agree
// with the docs while disagreeing with what an SDK actually sends, which is the
// class of failure #739 exists to close.
var routing = emu.PluginRoutingCatalog()

func main() {
	check := flag.Bool("check", false, "exit non-zero if the file is out of date instead of writing it")
	out := flag.String("out", "docs/services.md", "path to the services reference file")
	flag.Parse()

	names, err := registeredPlugins()
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-service-reference:", err)
		os.Exit(1)
	}

	existing, err := os.ReadFile(*out)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-service-reference: read %s: %v\n", *out, err)
		os.Exit(1)
	}

	updated, err := replaceMatrix(existing, names)
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-service-reference:", err)
		os.Exit(1)
	}

	if *check {
		if !bytes.Equal(existing, updated) {
			fmt.Fprintf(os.Stderr, "gen-service-reference: %s coverage matrix is out of date; run `make docs-reference` and commit the result\n", *out)
			os.Exit(1)
		}
		return
	}

	if bytes.Equal(existing, updated) {
		fmt.Printf("%s already up to date (%d plugins)\n", *out, len(names))
		return
	}
	if err := os.WriteFile(*out, updated, 0o644); err != nil { //nolint:gosec // docs file, world-readable is fine.
		fmt.Fprintln(os.Stderr, "gen-service-reference:", err)
		os.Exit(1)
	}
	fmt.Printf("updated %s (%d plugins)\n", *out, len(names))
}

// registeredPlugins boots the default registry and returns the sorted plugin
// names, verifying that metadata is complete in both directions.
func registeredPlugins() ([]string, error) {
	reg := emu.NewPluginRegistry()
	state := emu.NewMemoryStateManager()
	tc := emu.NewTimeController(time.Unix(0, 0).UTC())
	logger := emu.NewDefaultLogger(slog.LevelError, false)
	store := emu.NewEventStore(emu.EventStoreConfig{Enabled: false})

	if err := emu.RegisterDefaultPlugins(context.Background(), reg, state, tc, logger, store, nil); err != nil {
		return nil, fmt.Errorf("register default plugins: %w", err)
	}
	names, err := checkRouting(reg.Names(), routing)
	if err != nil {
		return nil, err
	}
	return names, checkCatalog(names, emu.RoutedServices())
}

// checkCatalog verifies that the operation catalog covers exactly the registered
// plugins. It takes both lists as parameters for the same reason checkRouting does:
// an untested drift check is one nobody knows still fires (#739).
//
// The catalog is generated from each plugin's dispatch switch, so this refusal only
// fires when the generated file is stale — and `make operation-catalog-check` runs
// before this tool in CI so that the failure names the right file. The refusal is
// still worth having: without it, a plugin the catalog does not cover would render a
// zero in the matrix, which reads as "routes no operations" rather than as an error.
func checkCatalog(registered, cataloged []string) error {
	inCatalog := make(map[string]bool, len(cataloged))
	for _, n := range cataloged {
		inCatalog[n] = true
	}
	for _, n := range registered {
		if !inCatalog[n] {
			return fmt.Errorf("plugin %q is registered but absent from the operation catalog; run `make operation-catalog` and commit the result", n)
		}
	}
	isRegistered := make(map[string]bool, len(registered))
	for _, n := range registered {
		isRegistered[n] = true
	}
	for _, n := range cataloged {
		if !isRegistered[n] {
			return fmt.Errorf("operation catalog covers %q, which is not a registered plugin; run `make operation-catalog` and commit the result", n)
		}
	}
	return nil
}

// checkRouting verifies that the routing table and the registered plugin names
// agree in both directions and returns the names sorted. It takes the table as a
// parameter rather than reading the package-level [routing] so that both refusals
// are reachable from a test — the drift check is the whole point of the -check
// flag, and an untested drift check is one nobody knows still fires (#739).
func checkRouting(names []string, table map[string]emu.PluginRouting) ([]string, error) {
	registered := make(map[string]bool, len(names))
	for _, n := range names {
		registered[n] = true
		if _, ok := table[n]; !ok {
			return nil, fmt.Errorf("plugin %q is registered but has no entry in emulator/routing.go; add one, citing the source of its target prefix, hosts and signing names", n)
		}
	}
	for n := range table {
		if !registered[n] {
			return nil, fmt.Errorf("routing entry %q does not correspond to a registered plugin; remove it from emulator/routing.go", n)
		}
	}
	sorted := make([]string, len(names))
	copy(sorted, names)
	sort.Strings(sorted)
	return sorted, nil
}

// replaceMatrix swaps the content between the begin/end markers in doc for a
// freshly rendered coverage matrix, leaving everything else untouched.
func replaceMatrix(doc []byte, names []string) ([]byte, error) {
	begin := bytes.Index(doc, []byte(beginMarker))
	end := bytes.Index(doc, []byte(endMarker))
	if begin < 0 || end < 0 || end < begin {
		return nil, fmt.Errorf("could not find %q ... %q markers in the document", beginMarker, endMarker)
	}

	total := 0
	for _, n := range names {
		total += len(emu.RoutedOperations(n))
	}

	var matrix bytes.Buffer
	fmt.Fprintln(&matrix, beginMarker)
	fmt.Fprintf(&matrix, "Substrate ships **%d built-in service plugins** routing **%d operations**. This\n", len(names), total)
	fmt.Fprintln(&matrix, "section is generated from the plugin registry and the operation catalog")
	fmt.Fprintln(&matrix, "(`make docs-reference`), so the counts and the plugin list cannot drift from the")
	fmt.Fprintln(&matrix, "implementation: the catalog is itself generated from each plugin's dispatch switch")
	fmt.Fprintln(&matrix, "(`make operation-catalog`) and is readable at run time through")
	fmt.Fprintln(&matrix, "`emulator.RoutedServices` and `emulator.RoutedOperations`. The live plugin count is")
	fmt.Fprintln(&matrix, "also available from the `/ready` endpoint (`curl http://localhost:4566/ready`).")
	fmt.Fprintln(&matrix, "Per-service operation, CloudFormation, and cost detail follows below the matrix.")
	fmt.Fprintln(&matrix)
	fmt.Fprintln(&matrix, "Two plugins route **0** operations, and that is their protocol rather than a gap:")
	fmt.Fprintln(&matrix, "`execute-api` serves a deployed API's own routes (AWS's action for it is the single")
	fmt.Fprintln(&matrix, "`execute-api:Invoke`), and `opensearch` dispatches on the HTTP method plus path")
	fmt.Fprintln(&matrix, "shape, as AWS's own per-verb `es:ESHttp*` actions reflect.")
	fmt.Fprintln(&matrix)
	fmt.Fprintln(&matrix, "| # | Service | Plugin name | Protocol | Operations |")
	fmt.Fprintln(&matrix, "|---|---------|-------------|----------|-----------:|")
	for i, n := range names {
		m := routing[n]
		fmt.Fprintf(&matrix, "| %d | %s | `%s` | %s | %d |\n", i+1, m.Display, n, m.Protocol, len(emu.RoutedOperations(n)))
	}
	fmt.Fprint(&matrix, endMarker)

	var result bytes.Buffer
	result.Write(doc[:begin])
	result.Write(matrix.Bytes())
	result.Write(doc[end+len(endMarker):])
	return result.Bytes(), nil
}
